spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=statistics
    username: postgres
    password: postgres
  application:
    name: MetricsConsumer
server:
  port: 8081